plugin: aws_ec2
regions:
  - "us-east-1"
filters:
  tag:role: master
  tag:environment: prod
keyed_groups:
  - key: tags['role']
    prefix: "role_"
    separator: ""
hostnames:
  - "private-ip-address"
compose:
  ansible_user: "'ubuntu'"
